# Creation date : 22.08.2022
# Created by : CSR
# Updated : + service de création automatique de la DB "db_passion_lecture"
# Description : Create two containers (one for the db and the other one for phpMyAdmin)

version: '3.3'

services:
  db:
    image: mysql:8.0.30
    container_name: db_passion_lecture
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
      MYSQL_DATABASE: db_passion_lecture # <-- création automatique ici
    restart: always
    ports:
      - '6033:3306'
    volumes:
      - dbdata:/var/lib/mysql
      - ./scripts:/scripts
      - ./init:/docker-entrypoint-initdb.d # <-- exécute automatiquement les .sql

volumes:
  dbdata:
